//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash_Tank__Front_End_Web_.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDashTankService")]
    public interface IDashTankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/Login", ReplyAction="http://tempuri.org/IDashTankService/LoginResponse")]
        int Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/Login", ReplyAction="http://tempuri.org/IDashTankService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/UserRegistration", ReplyAction="http://tempuri.org/IDashTankService/UserRegistrationResponse")]
        int UserRegistration(string name, string surname, string email, string contact, string Password, string ConfirmPassword, string UserType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/UserRegistration", ReplyAction="http://tempuri.org/IDashTankService/UserRegistrationResponse")]
        System.Threading.Tasks.Task<int> UserRegistrationAsync(string name, string surname, string email, string contact, string Password, string ConfirmPassword, string UserType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddOrder", ReplyAction="http://tempuri.org/IDashTankService/AddOrderResponse")]
        int AddOrder(System.DateTime OrderDate, System.DateTime OrderEstimatedArrival, string CarNumPlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddOrder", ReplyAction="http://tempuri.org/IDashTankService/AddOrderResponse")]
        System.Threading.Tasks.Task<int> AddOrderAsync(System.DateTime OrderDate, System.DateTime OrderEstimatedArrival, string CarNumPlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddDriverInfor", ReplyAction="http://tempuri.org/IDashTankService/AddDriverInforResponse")]
        int AddDriverInfor(System.DateTime DOB, string numPlate, string VehicleType, string gender, string LicenceNum, string VehicleName, int NumOrders, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddDriverInfor", ReplyAction="http://tempuri.org/IDashTankService/AddDriverInforResponse")]
        System.Threading.Tasks.Task<int> AddDriverInforAsync(System.DateTime DOB, string numPlate, string VehicleType, string gender, string LicenceNum, string VehicleName, int NumOrders, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddClientInfo", ReplyAction="http://tempuri.org/IDashTankService/AddClientInfoResponse")]
        int AddClientInfo(string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddClientInfo", ReplyAction="http://tempuri.org/IDashTankService/AddClientInfoResponse")]
        System.Threading.Tasks.Task<int> AddClientInfoAsync(string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddAdmin", ReplyAction="http://tempuri.org/IDashTankService/AddAdminResponse")]
        int AddAdmin(string AdminAccess, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddAdmin", ReplyAction="http://tempuri.org/IDashTankService/AddAdminResponse")]
        System.Threading.Tasks.Task<int> AddAdminAsync(string AdminAccess, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddSupplierInfor", ReplyAction="http://tempuri.org/IDashTankService/AddSupplierInforResponse")]
        int AddSupplierInfor(string Address, string GarageName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddSupplierInfor", ReplyAction="http://tempuri.org/IDashTankService/AddSupplierInforResponse")]
        System.Threading.Tasks.Task<int> AddSupplierInforAsync(string Address, string GarageName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddToCart", ReplyAction="http://tempuri.org/IDashTankService/AddToCartResponse")]
        int AddToCart(int itemQuantity, decimal itemPrice, decimal cartPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddToCart", ReplyAction="http://tempuri.org/IDashTankService/AddToCartResponse")]
        System.Threading.Tasks.Task<int> AddToCartAsync(int itemQuantity, decimal itemPrice, decimal cartPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddProduct", ReplyAction="http://tempuri.org/IDashTankService/AddProductResponse")]
        int AddProduct(string ProName, string ProDescription, int SaleStatus, decimal ProPrice, decimal ProSalePrice, string ProImage, string ProHistory, string ProType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddProduct", ReplyAction="http://tempuri.org/IDashTankService/AddProductResponse")]
        System.Threading.Tasks.Task<int> AddProductAsync(string ProName, string ProDescription, int SaleStatus, decimal ProPrice, decimal ProSalePrice, string ProImage, string ProHistory, string ProType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddPromotion", ReplyAction="http://tempuri.org/IDashTankService/AddPromotionResponse")]
        int AddPromotion(string PromoCode, decimal PromoAmmount, int ValidityStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddPromotion", ReplyAction="http://tempuri.org/IDashTankService/AddPromotionResponse")]
        System.Threading.Tasks.Task<int> AddPromotionAsync(string PromoCode, decimal PromoAmmount, int ValidityStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddTransaction", ReplyAction="http://tempuri.org/IDashTankService/AddTransactionResponse")]
        int AddTransaction(System.DateTime TransDate, decimal TransAmmount, int TransStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddTransaction", ReplyAction="http://tempuri.org/IDashTankService/AddTransactionResponse")]
        System.Threading.Tasks.Task<int> AddTransactionAsync(System.DateTime TransDate, decimal TransAmmount, int TransStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddReview", ReplyAction="http://tempuri.org/IDashTankService/AddReviewResponse")]
        int AddReview(int rating, string Reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddReview", ReplyAction="http://tempuri.org/IDashTankService/AddReviewResponse")]
        System.Threading.Tasks.Task<int> AddReviewAsync(int rating, string Reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddRefund", ReplyAction="http://tempuri.org/IDashTankService/AddRefundResponse")]
        int AddRefund(string Reason, string AdminFeedback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashTankService/AddRefund", ReplyAction="http://tempuri.org/IDashTankService/AddRefundResponse")]
        System.Threading.Tasks.Task<int> AddRefundAsync(string Reason, string AdminFeedback);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDashTankServiceChannel : Dash_Tank__Front_End_Web_.ServiceReference1.IDashTankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DashTankServiceClient : System.ServiceModel.ClientBase<Dash_Tank__Front_End_Web_.ServiceReference1.IDashTankService>, Dash_Tank__Front_End_Web_.ServiceReference1.IDashTankService {
        
        public DashTankServiceClient() {
        }
        
        public DashTankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DashTankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashTankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashTankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
        
        public int UserRegistration(string name, string surname, string email, string contact, string Password, string ConfirmPassword, string UserType) {
            return base.Channel.UserRegistration(name, surname, email, contact, Password, ConfirmPassword, UserType);
        }
        
        public System.Threading.Tasks.Task<int> UserRegistrationAsync(string name, string surname, string email, string contact, string Password, string ConfirmPassword, string UserType) {
            return base.Channel.UserRegistrationAsync(name, surname, email, contact, Password, ConfirmPassword, UserType);
        }
        
        public int AddOrder(System.DateTime OrderDate, System.DateTime OrderEstimatedArrival, string CarNumPlate) {
            return base.Channel.AddOrder(OrderDate, OrderEstimatedArrival, CarNumPlate);
        }
        
        public System.Threading.Tasks.Task<int> AddOrderAsync(System.DateTime OrderDate, System.DateTime OrderEstimatedArrival, string CarNumPlate) {
            return base.Channel.AddOrderAsync(OrderDate, OrderEstimatedArrival, CarNumPlate);
        }
        
        public int AddDriverInfor(System.DateTime DOB, string numPlate, string VehicleType, string gender, string LicenceNum, string VehicleName, int NumOrders, string image) {
            return base.Channel.AddDriverInfor(DOB, numPlate, VehicleType, gender, LicenceNum, VehicleName, NumOrders, image);
        }
        
        public System.Threading.Tasks.Task<int> AddDriverInforAsync(System.DateTime DOB, string numPlate, string VehicleType, string gender, string LicenceNum, string VehicleName, int NumOrders, string image) {
            return base.Channel.AddDriverInforAsync(DOB, numPlate, VehicleType, gender, LicenceNum, VehicleName, NumOrders, image);
        }
        
        public int AddClientInfo(string image) {
            return base.Channel.AddClientInfo(image);
        }
        
        public System.Threading.Tasks.Task<int> AddClientInfoAsync(string image) {
            return base.Channel.AddClientInfoAsync(image);
        }
        
        public int AddAdmin(string AdminAccess, string image) {
            return base.Channel.AddAdmin(AdminAccess, image);
        }
        
        public System.Threading.Tasks.Task<int> AddAdminAsync(string AdminAccess, string image) {
            return base.Channel.AddAdminAsync(AdminAccess, image);
        }
        
        public int AddSupplierInfor(string Address, string GarageName) {
            return base.Channel.AddSupplierInfor(Address, GarageName);
        }
        
        public System.Threading.Tasks.Task<int> AddSupplierInforAsync(string Address, string GarageName) {
            return base.Channel.AddSupplierInforAsync(Address, GarageName);
        }
        
        public int AddToCart(int itemQuantity, decimal itemPrice, decimal cartPrice) {
            return base.Channel.AddToCart(itemQuantity, itemPrice, cartPrice);
        }
        
        public System.Threading.Tasks.Task<int> AddToCartAsync(int itemQuantity, decimal itemPrice, decimal cartPrice) {
            return base.Channel.AddToCartAsync(itemQuantity, itemPrice, cartPrice);
        }
        
        public int AddProduct(string ProName, string ProDescription, int SaleStatus, decimal ProPrice, decimal ProSalePrice, string ProImage, string ProHistory, string ProType) {
            return base.Channel.AddProduct(ProName, ProDescription, SaleStatus, ProPrice, ProSalePrice, ProImage, ProHistory, ProType);
        }
        
        public System.Threading.Tasks.Task<int> AddProductAsync(string ProName, string ProDescription, int SaleStatus, decimal ProPrice, decimal ProSalePrice, string ProImage, string ProHistory, string ProType) {
            return base.Channel.AddProductAsync(ProName, ProDescription, SaleStatus, ProPrice, ProSalePrice, ProImage, ProHistory, ProType);
        }
        
        public int AddPromotion(string PromoCode, decimal PromoAmmount, int ValidityStatus) {
            return base.Channel.AddPromotion(PromoCode, PromoAmmount, ValidityStatus);
        }
        
        public System.Threading.Tasks.Task<int> AddPromotionAsync(string PromoCode, decimal PromoAmmount, int ValidityStatus) {
            return base.Channel.AddPromotionAsync(PromoCode, PromoAmmount, ValidityStatus);
        }
        
        public int AddTransaction(System.DateTime TransDate, decimal TransAmmount, int TransStatus) {
            return base.Channel.AddTransaction(TransDate, TransAmmount, TransStatus);
        }
        
        public System.Threading.Tasks.Task<int> AddTransactionAsync(System.DateTime TransDate, decimal TransAmmount, int TransStatus) {
            return base.Channel.AddTransactionAsync(TransDate, TransAmmount, TransStatus);
        }
        
        public int AddReview(int rating, string Reason) {
            return base.Channel.AddReview(rating, Reason);
        }
        
        public System.Threading.Tasks.Task<int> AddReviewAsync(int rating, string Reason) {
            return base.Channel.AddReviewAsync(rating, Reason);
        }
        
        public int AddRefund(string Reason, string AdminFeedback) {
            return base.Channel.AddRefund(Reason, AdminFeedback);
        }
        
        public System.Threading.Tasks.Task<int> AddRefundAsync(string Reason, string AdminFeedback) {
            return base.Channel.AddRefundAsync(Reason, AdminFeedback);
        }
    }
}
